# DB Version: 18
# OS Type: linux
# DB Type: oltp
# Total Memory (RAM): 1 GB
# CPUs num: 2
# Data Storage: ssd
# https://pgtune.leopard.in.ua/

max_connections = 300
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.9
wal_buffers = 7864kB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 436kB
huge_pages = off
min_wal_size = 2GB
max_wal_size = 8GB
checkpoint_timeout = 30min
log_min_duration_statement = 100
