[options]
# Database Settings
data_dir=/var/lib/odoo
db_user=kni
db_password=kni
dbfilter=^kni$
db_name=False
db_maxconn=64
list_db=False

# Logs Settings
log_level=info

# Service Settings
addons_path=
    /mnt/extra-addons,
    /mnt/enterprise,
    /mnt/design-themes,
    /mnt/odoo/addons,
    /mnt/odoo/odoo/addons

gevent_port=8072
http_port=8069
http_interface=0.0.0.0
proxy_mode=True
unaccent=False
server_wide_modules=None

# Tuning Options
workers=2
max_cron_threads=2
limit_time_cpu=600
limit_time_real=1200
limit_time_real_cron=2400
# Default is 2048 * 1024 * 1024 ~ 2.0G
limit_memory_soft=536870912
# Default is 2048 * 1024 * 1024 ~ 2.0G
limit_memory_hard=1610612736
limit_request=8196
