[awsbucket]
type = s3
provider = AWS
access_key_id = < REDACTED >
secret_access_key = < REDACTED >
region = eu-north-1

[backup-crypt]
type = crypt
remote = awsbucket:odoo-backups-crypt
filename_encryption = off
directory_name_encryption = false
password = < REDACTED >