[Unit]
Requisite=srv-secure.mount var-lib-postgresql.mount var-lib-docker.mount var-lib-containerd.mount etc-odoo.mount var-log-nginx.mount var-log-postgresql.mount var-lib-nginx.mount
After=srv-secure.mount var-lib-postgresql.mount var-lib-docker.mount var-lib-containerd.mount etc-odoo.mount var-log-nginx.mount var-log-postgresql.mount var-lib-nginx.mount
PartOf=odoo-app.target
ConditionPathIsMountPoint=/srv/secure
