[Unit]
RequiresMountsFor=/srv/secure /var/lib/postgresql /var/lib/docker /var/lib/containerd /etc/odoo /var/log/nginx /var/log/postgresql /var/lib/nginx
PartOf=odoo-app.target
ConditionPathIsMountPoint=/srv/secure
