[options]
# Database Settings
data_dir=/var/lib/odoo
db_name={{ uid }}
dbfilter=^{{ uid }}$
db_user={{ uid }}
db_password={{ pw }}
db_maxconn=8
list_db=False

# Logs Settings
log_level=info

# Service Settings
addons_path=
    {%- for mod in modules %}
    /mnt/{{ mod }},
    {%- endfor %}
    /mnt/odoo/addons

gevent_port=8072
http_port=8069
http_interface=0.0.0.0
proxy_mode=True
unaccent=False
server_wide_modules=None

# Tuning Options
workers=2
max_cron_threads=0
limit_time_real=1200
limit_time_cpu=2400
limit_time_real_cron=2400
# Default is 2048 * 1024 * 1024 ~ 2.0G
limit_memory_soft=836870912
# Default is 2048 * 1024 * 1024 ~ 2.0G
limit_memory_hard=1610612736
limit_request=256
with_demo=False
