server {
    listen 9000 ssl;
    listen [::]:9000 ssl;
    server_name agent16.eniemela.fi;

    proxy_read_timeout 24h;
    proxy_connect_timeout 24h;
    proxy_send_timeout 24h;

    ssl_protocols TLSv1.3;
    ssl_certificate /etc/letsencrypt/live/eniemela.fi/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eniemela.fi/privkey.pem;

    ssl_session_cache shared:TLS:2m;
    ssl_buffer_size 4k;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001]; # Cloudflare

    # Set HSTS to 365 days
    add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload' always;

    # Basic Authentication
    auth_basic           "Admin Area";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://127.0.0.1:8000;
    }
}
